dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= qcom-ipq807x-phoenix.dtb qcom-ipq807x-hendrix.dtb \
                           qcom-ipq807x-mr46.dtb qcom-ipq807x-mr56.dtb \
                           qcom-ipq807x-mr36.dtb qcom-ipq807x-mr76.dtb \
                           qcom-ipq807x-mr46e.dtb qcom-ipq807x-mr86.dtb \
                           qcom-ipq807x-mr44.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
